// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:go_router/go_router.dart';

import '../configs/service_locator/service_locator.dart';
import 'screens/home/home_store.dart';
import 'screens/home/widgets/home_screen.dart';

final class Routes with ServiceLocatorMixin {
  static const home = '/';

  static GoRouter get routerConfig => Routes._()._router;

  Routes._();

  GoRouter get _router {
    return GoRouter(
      initialLocation: home,
      debugLogDiagnostics: true,
      routes: [
        GoRoute(
          path: home,
          builder: (context, state) {
            return HomeScreen(
              store: HomeStore(productRepository: instance()),
            );
          },
        ),
      ],
    );
  }
}
