name: favoriti
description: "Explore produtos, marque favoritos e gerencie suas escolhas"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  result_dart: ^2.0.0
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  auto_injector: ^2.0.5
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  intl: ^0.20.1
  go_router: ^14.6.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
